/**
 * Stack Overflow For Teams Read APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { string } from '../schema';
import { BaseController } from './baseController';

export class CommentsController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getAllComments(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/comments');
    return req.call(requestOptions);
  }

  /**
   * @param commentIds
   * @return Response from the API call
   */
  async getCommentsByIDs(
    commentIds: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ commentIds: [commentIds, string()] });
    req.appendTemplatePath`/comments/${mapped.commentIds}`;
    return req.call(requestOptions);
  }
}
