/**
 * Stack Overflow For Teams Read APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { string } from '../schema';
import { BaseController } from './baseController';

export class RevisionsController extends BaseController {
  /**
   * @param revisionIds
   * @return Response from the API call
   */
  async newRequest(
    revisionIds: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ revisionIds: [revisionIds, string()] });
    req.appendTemplatePath`/revisions/${mapped.revisionIds}`;
    return req.call(requestOptions);
  }
}
