/**
 * Stack Overflow For Teams Read APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { number } from '../schema';
import { BaseController } from './baseController';

export class SitesController extends BaseController {
  /**
   * @param pagesize
   * @return Response from the API call
   */
  async getAllSites(
    pagesize: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/sites');
    const mapped = req.prepareArgs({ pagesize: [pagesize, number()] });
    req.query('pagesize', mapped.pagesize);
    return req.call(requestOptions);
  }
}
