/**
 * Stack Overflow For Teams Read APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { string } from '../schema';
import { BaseController } from './baseController';

export class SuggestedEditsController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getSuggestedEdits(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/suggested-edits');
    return req.call(requestOptions);
  }

  /**
   * @param editIds
   * @return Response from the API call
   */
  async getSuggestedEditsByIDsPaged(
    editIds: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ editIds: [editIds, string()] });
    req.appendTemplatePath`/suggested-edits/${mapped.editIds}`;
    return req.call(requestOptions);
  }
}
